server:
  port: 3030

spring:
  datasource:
    password: hr
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: hr
    
    
  jpa:
   hibernate:
     ddl-auto: update
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   show-sql: true