server:
  port: 4050

spring:
  datasource:
    password: hr
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: hr
    
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  application:
    name: Payment-service
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:  endpoints:    web:      exposure:        include:        - "*" 
        
info:
  name: Payment Service
    
    
    
    